In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

# data import

In [2]:
dataset = pd.read_csv("dataset.csv")

In [3]:
data =dataset

# data replacement

In [4]:
data['MultipleLines']   .replace({'No':'No','Yes':'Yes','No phone service':'No'},inplace=True)
data['OnlineSecurity']  .replace({'No':'No','Yes':'Yes','No internet service':'No'},inplace=True)
data['OnlineBackup']    .replace({'No':'No','Yes':'Yes','No internet service':'No'},inplace=True)
data['DeviceProtection'].replace({'No':'No','Yes':'Yes','No internet service':'No'},inplace=True)
data['TechSupport']     .replace({'No':'No','Yes':'Yes','No internet service':'No'},inplace=True)
data['StreamingTV']     .replace({'No':'No','Yes':'Yes','No internet service':'No'},inplace=True)
data['StreamingMovies'] .replace({'No':'No','Yes':'Yes','No internet service':'No'},inplace=True)

In [5]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [6]:
data

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female            NaN     Yes         No     NaN   
1     5575-GNVDE    Male            NaN      No         No    34.0   
2     3668-QPYBK    Male            NaN      No         No     2.0   
3     7795-CFOCW    Male            NaN      No         No    45.0   
4     9237-HQITU  Female            NaN      No         No     2.0   
5     9305-CDSKC  Female            NaN      No         No     8.0   
6     1452-KIOVK    Male            NaN      No        Yes    22.0   
7     6713-OKOMC  Female            NaN      No         No    10.0   
8     7892-POOKP  Female            NaN     Yes         No    28.0   
9     6388-TABGU    Male            NaN      No        Yes    62.0   
10    9763-GRSKD    Male            NaN     Yes        Yes    13.0   
11    7469-LKBCI    Male            NaN      No         No    16.0   
12    8091-TTVAX    Male            NaN     Yes         No    58.0   
13    0280-XJGEX    Male            NaN      No         No    49.0   
14    5129-JLPIS    Male            NaN      No         No    25.0   
15    3655-SNQYZ  Female            NaN     Yes        Yes    69.0   
16    8191-XWSZG  Female            NaN      No         No    52.0   
17    9959-WOFKT    Male            NaN      No        Yes    71.0   
18    4190-MFLUW  Female            NaN     Yes        Yes    10.0   
19    4183-MYFRB  Female            NaN      No         No    21.0   
20    8779-QRDMV    Male            1.0      No         No     NaN   
21    1680-VDCWW    Male            NaN     Yes         No    12.0   
22    1066-JKSGK    Male            NaN      No         No     NaN   
23    3638-WEABW  Female            NaN     Yes         No    58.0   
24    6322-HRPFA    Male            NaN     Yes        Yes    49.0   
25    6865-JZNKO  Female            NaN      No         No    30.0   
26    6467-CHFZW    Male            NaN     Yes        Yes    47.0   
27    8665-UTDHZ    Male            NaN     Yes        Yes     NaN   
28    5248-YGIJN    Male            NaN     Yes         No    72.0   
29    8773-HHUOZ  Female            NaN      No        Yes    17.0   
...          ...     ...            ...     ...        ...     ...   
7013  1685-BQULA  Female            0.0      No         No    40.0   
7014  9053-EJUNL    Male            0.0      No         No    41.0   
7015  0666-UXTJO    Male            1.0     Yes         No    34.0   
7016  1471-GIQKQ  Female            0.0      No         No     1.0   
7017  4807-IZYOZ  Female            0.0      No         No    51.0   
7018  1122-JWTJW    Male            0.0     Yes        Yes     1.0   
7019  9710-NJERN  Female            0.0      No         No    39.0   
7020  9837-FWLCH    Male            0.0     Yes        Yes    12.0   
7021  1699-HPSBG    Male            0.0      No         No    12.0   
7022  7203-OYKCT    Male            0.0      No         No    72.0   
7023  1035-IPQPU  Female            1.0     Yes         No    63.0   
7024  7398-LXGYX    Male            0.0     Yes         No    44.0   
7025  2823-LKABH  Female            0.0      No         No    18.0   
7026  8775-CEBBJ  Female            0.0      No         No     9.0   
7027  0550-DCXLH    Male            0.0      No         No    13.0   
7028  9281-CEDRU  Female            0.0     Yes         No    68.0   
7029  2235-DWLJU  Female            1.0      No         No     6.0   
7030  0871-OPBXW  Female            0.0      No         No     2.0   
7031  3605-JISKB    Male            1.0     Yes         No    55.0   
7032  6894-LFHLY    Male            1.0      No         No     1.0   
7033  9767-FFLEM    Male            0.0      No         No    38.0   
7034  0639-TSIQW  Female            0.0      No         No    67.0   
7035  8456-QDAVC    Male            0.0      No         No    19.0   
7036  7750-EYXWZ  Female            0.0      No         No    12.0   
7037  2569-WGERO  Female            0.0      No         No    72.0   
7038  6840-RESVB

In [411]:
data

SeniorCitizen  Partner  Dependents        tenure  OnlineSecurity  \
20              1.0        0           0 -2.033755e-16               0   
30              1.0        1           0  1.572534e+00               1   
31              1.0        1           0 -1.285841e+00               0   
34              1.0        0           0 -2.033755e-16               0   
47              0.0        0           0 -1.285841e+00               0   
48              0.0        0           0  7.854456e-01               1   
49              0.0        1           1  1.489683e+00               1   
50              1.0        0           0  4.126140e-01               0   
51              0.0        0           0 -7.473064e-01               1   
52              1.0        1           0 -3.330491e-01               1   
53              1.0        1           0 -1.037286e+00               0   
54              1.0        1           1  1.116851e+00               1   
55              1.0        0           0 -6.230292e-01               0   
56              0.0        1           1  1.241129e+00               1   
57              1.0        1           1  1.365406e+00               0   
58              0.0        1           1  3.978247e-02               0   
59              0.0        0           0  1.613960e+00               0   
60              0.0        1           0  5.783169e-01               0   
61              0.0        0           0  1.116851e+00               0   
62              0.0        1           0  1.613960e+00               1   
63              0.0        1           1 -6.230292e-01               0   
64              0.0        0           0 -9.958607e-01               0   
65              0.0        0           0 -1.244415e+00               0   
66              0.0        1           0  5.783169e-01               0   
67              0.0        0           0 -8.449471e-02               0   
68              0.0        1           1  7.025941e-01               0   
69              0.0        0           0 -9.544350e-01               1   
70              0.0        0           0 -2.033755e-16               0   
71              0.0        1           1  7.854456e-01               0   
72              1.0        1           1  1.282554e+00               1   
...             ...      ...         ...           ...             ...   
7013            0.0        0           0  2.883368e-01               0   
7014            0.0        0           0  3.297626e-01               0   
7015            1.0        1           0  3.978247e-02               0   
7016            0.0        0           0 -1.327267e+00               0   
7017            0.0        0           0  7.440198e-01               0   
7018            0.0        1           1 -1.327267e+00               0   
7019            0.0        0           0  2.469111e-01               0   
7020            0.0        1           1 -8.715835e-01               0   
7021            0.0        0           0 -8.715835e-01               0   
7022            0.0        0           0  1.613960e+00               0   
7023            1.0        1           0  1.241129e+00               0   
7024            0.0        1           0  4.540398e-01               1   
7025            0.0        0           0 -6.230292e-01               0   
7026            0.0        0           0 -9.958607e-01               0   
7027            0.0        0           0 -8.301578e-01               0   
7028            0.0        1           0  1.448257e+00               0   
7029            1.0        0           0 -1.120138e+00               0   
7030            0.0        0           0 -1.285841e+00               0   
7031            1.0        1           0  9.097228e-01               1   
7032            1.0        0           0 -1.327267e+00               0   
7033            0.0        0           0  2.054854e-01               0   
7034            0.0        0           0  1.406831e+00               1   
7035      

# Missing values treatment



In [ ]:
data.isna().sum()

In [9]:
data.dropna(subset=["SeniorCitizen"],inplace=True)
t_mean = data['tenure'].mean()
fills  = {"tenure":t_mean}
data.fillna(fills,inplace=True)

In [10]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [11]:
data.drop("customerID",axis=1,inplace=True) #drop index column

# label Encoder

In [407]:
from sklearn.preprocessing import LabelEncoder #importing labelEncoder

In [370]:
d={}                                                # new data dictionary for saveing labelEncoders objects
for i in data.columns :                             # looping data2 coluoms  
    if data[i].dtype == "object":                   # select only object attributes 
        d[i]=LabelEncoder()                         #new labelencoder object for each attribute with object datatype
        d[i].fit(data[i])                           #fitting dataframe attribute
        data[i]=d[i].transform(data[i])             #transform attribute and save it in dataframe

# Feature engineering

In [ ]:
data.head

In [15]:
data.corr()

gender  SeniorCitizen   Partner  Dependents    tenure  \
gender            1.000000      -0.001843 -0.001117    0.010372  0.010159   
SeniorCitizen    -0.001843       1.000000  0.016189   -0.211728  0.013413   
Partner          -0.001117       0.016189  1.000000    0.452715  0.371699   
Dependents        0.010372      -0.211728  0.452715    1.000000  0.158733   
tenure            0.010159       0.013413  0.371699    0.158733  1.000000   
PhoneService     -0.006573       0.008642  0.018137   -0.002198  0.005327   
MultipleLines    -0.007478       0.143319  0.141785   -0.024691  0.322833   
InternetService  -0.001296      -0.033157  0.001899    0.046372 -0.028361   
OnlineSecurity   -0.017349      -0.038169  0.143715    0.079961  0.319159   
OnlineBackup     -0.014046       0.067676  0.140759    0.021881  0.353827   
DeviceProtection -0.001707       0.059953  0.155519    0.015251  0.352562   
TechSupport      -0.007919      -0.060909  0.118200    0.063128  0.317358   
StreamingTV      -0.008036       0.105829  0.124931   -0.017366  0.270561   
StreamingMovies  -0.010444       0.120248  0.118511   -0.039339  0.276877   
Contract          0.000409      -0.143388  0.294862    0.243539  0.666686   
PaperlessBilling -0.010208       0.156808 -0.014115   -0.110112  0.000267   
PaymentMethod     0.017939      -0.038678 -0.155896   -0.040641 -0.358102   
MonthlyCharges   -0.014036       0.221101  0.097502   -0.114972  0.235611   
TotalCharges      0.000246       0.102831  0.319585    0.063482  0.814056   
Churn            -0.008900       0.151711 -0.150409   -0.165001 -0.341024   

                  PhoneService  MultipleLines  InternetService  \
gender               -0.006573      -0.007478        -0.001296   
SeniorCitizen         0.008642       0.143319        -0.033157   
Partner               0.018137       0.141785         0.001899   
Dependents           -0.002198      -0.024691         0.046372   
tenure                0.005327       0.322833        -0.028361   
PhoneService          1.000000       0.279821         0.388016   
MultipleLines         0.279821       1.000000         0.010892   
InternetService       0.388016       0.010892         1.000000   
OnlineSecurity       -0.093090       0.098676        -0.392091   
OnlineBackup         -0.052637       0.202050        -0.313430   
DeviceProtection     -0.072272       0.200445        -0.308377   
TechSupport          -0.097036       0.099731        -0.390028   
StreamingTV          -0.024283       0.253811        -0.244197   
StreamingMovies      -0.034432       0.256994        -0.253056   
Contract              0.001503       0.105916         0.100050   
PaperlessBilling      0.015496       0.162210        -0.138695   
PaymentMethod        -0.003905      -0.169946         0.087385   
MonthlyCharges        0.246692       0.489031        -0.324616   
TotalCharges          0.112008       0.467299        -0.176228   
Churn                 0.011782       0.039821        -0.047995   

                  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
gender                 -0.017349     -0.014046         -0.001707    -0.007919   
SeniorCitizen          -0.038169      0.067676          0.059953    -0.060909   
Partner                 0.143715      0.140759          0.155519     0.118200   
Dependents              0.079961      0.021881          0.015251     0.063128   
tenure                  0.319159      0.353827          0.352562     0.317358   
PhoneService           -0.093090     -0.052637         -0.072272    -0.097036   
MultipleLines           0.098676      0.202050          0.200445     0.099731   
InternetService        -0.392091     -0.313430         -0.308377    -0.390028   
OnlineSecurity          1.000000      0.283705          0.276372     0.354408   
OnlineBackup            0.283705      1.000000          0.306286     0.294828   
DeviceProtection        0.276372      0.306286          1.000000     0.333269   
TechSupport             0.354408      0.294

In [16]:
data.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [17]:
data.drop('gender',axis=1,inplace=True)
data.drop('PhoneService',axis=1,inplace=True)
data.drop('MultipleLines',axis=1,inplace=True)
data.drop('InternetService',axis=1,inplace=True)
data.drop('OnlineBackup',axis=1,inplace=True)
data.drop('DeviceProtection',axis=1,inplace=True)
data.drop('StreamingTV',axis=1,inplace=True)
data.drop('StreamingMovies',axis=1,inplace=True)
data.drop('PaymentMethod',axis=1,inplace=True)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7000 entries, 20 to 7042
Data columns (total 11 columns):
SeniorCitizen       7000 non-null float64
Partner             7000 non-null int32
Dependents          7000 non-null int32
tenure              7000 non-null float64
OnlineSecurity      7000 non-null int32
TechSupport         7000 non-null int32
Contract            7000 non-null int32
PaperlessBilling    7000 non-null int32
MonthlyCharges      7000 non-null float64
TotalCharges        7000 non-null float64
Churn               7000 non-null int32
dtypes: float64(4), int32(7)
memory usage: 464.8 KB


In [19]:
data.head()

SeniorCitizen  Partner  Dependents     tenure  OnlineSecurity  \
20            1.0        0           0  33.039667               0   
30            1.0        1           0  71.000000               1   
31            1.0        1           0   2.000000               0   
34            1.0        0           0  33.039667               0   
47            0.0        0           0   2.000000               0   

    TechSupport  Contract  PaperlessBilling  MonthlyCharges  TotalCharges  \
20            0         0                 1           39.65         39.65   
30            1         2                 1           96.35       6766.95   
31            0         0                 1           95.50        181.65   
34            0         0                 0           45.25         45.25   
47            0         0                 1           80.65        144.15   

    Churn  
20      1  
30      0  
31      0  
34      0  
47      1

# Standardization
## z-score

In [21]:
data["tenure"]        =(data["tenure"]-data["tenure"].mean())/data["tenure"].std() #standarization z-score=(X-mean)/std
data["MonthlyCharges"]=(data["MonthlyCharges"]-data["MonthlyCharges"].mean())/data["MonthlyCharges"].std()
data["TotalCharges"]  =(data["TotalCharges"]-data["TotalCharges"].mean())/data["TotalCharges"].std()

In [210]:
data.corr()

SeniorCitizen   Partner  Dependents    tenure  \
SeniorCitizen          1.000000  0.016189   -0.211728  0.013413   
Partner                0.016189  1.000000    0.452715  0.371699   
Dependents            -0.211728  0.452715    1.000000  0.158733   
tenure                 0.013413  0.371699    0.158733  1.000000   
OnlineSecurity        -0.038169  0.143715    0.079961  0.319159   
TechSupport           -0.060909  0.118200    0.063128  0.317358   
Contract              -0.143388  0.294862    0.243539  0.666686   
PaperlessBilling       0.156808 -0.014115   -0.110112  0.000267   
MonthlyCharges         0.221101  0.097502   -0.114972  0.235611   
TotalCharges           0.102831  0.319585    0.063482  0.814056   
Churn                  0.151711 -0.150409   -0.165001 -0.341024   

                  OnlineSecurity  TechSupport  Contract  PaperlessBilling  \
SeniorCitizen          -0.038169    -0.060909 -0.143388          0.156808   
Partner                 0.143715     0.118200  0.294862         -0.014115   
Dependents              0.079961     0.063128  0.243539         -0.110112   
tenure                  0.319159     0.317358  0.666686          0.000267   
OnlineSecurity          1.000000     0.354408  0.245012         -0.002785   
TechSupport             0.354408     1.000000  0.293471          0.038365   
Contract                0.245012     0.293471  1.000000         -0.176011   
PaperlessBilling       -0.002785     0.038365 -0.176011          1.000000   
MonthlyCharges          0.297647     0.338693 -0.074826          0.351494   
TotalCharges            0.412629     0.432912  0.448865          0.158300   
Churn                  -0.169605    -0.164545 -0.396139          0.191136   

                  MonthlyCharges  TotalCharges     Churn  
SeniorCitizen           0.221101      0.102831  0.151711  
Partner                 0.097502      0.319585 -0.150409  
Dependents             -0.114972      0.063482 -0.165001  
tenure                  0.235611      0.814056 -0.341024  
OnlineSecurity          0.297647      0.412629 -0.169605  
TechSupport             0.338693      0.432912 -0.164545  
Contract               -0.074826      0.448865 -0.396139  
PaperlessBilling        0.351494      0.158300  0.191136  
MonthlyCharges          1.000000      0.650150  0.193337  
TotalCharges            0.650150      1.000000 -0.199319  
Churn                   0.193337     -0.199319  1.000000

# KNN

In [373]:
X = data.iloc[:, 2:9].values
y = data.iloc[:, 10].values

In [374]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [375]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [379]:
from sklearn.neighbors import KNeighborsClassifier
knnclassifier = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
knnclassifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=15, p=2,
           weights='uniform')

In [380]:
print("Test set predictions:", knnclassifier.predict(X_test))

Test set predictions: [0 0 0 ... 0 0 0]


In [381]:
print("Test set accuracy: {:.2f}".format(knnclassifier.score(X_test, y_test)))

Test set accuracy: 0.80


In [434]:
y_pred = knnclassifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [383]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1181,  112],
       [ 245,  212]], dtype=int64)

# Logistic Regression

In [328]:
from sklearn.linear_model import LogisticRegression
LRclassifier = LogisticRegression(random_state = 0)
LRclassifier.fit(X_train, y_train)

C:\Users\mossalam\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [329]:
y_pred = LRclassifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [330]:
print("Test set accuracy: {:.2f}".format(LRclassifier.score(X_test, y_test)))

Test set accuracy: 0.80


In [372]:
LRclassifier.score(X_test, y_test)

0.7954285714285714

In [331]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1169,  124],
       [ 234,  223]], dtype=int64)

# naive bayes
### Gaussian

In [384]:
from sklearn.naive_bayes import GaussianNB
NBclassifier = GaussianNB()
NBclassifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [385]:
y_pred = NBclassifier.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [386]:
print("Test set accuracy: {:.2f}".format(NBclassifier.score(X_test, y_test)))

Test set accuracy: 0.75


In [335]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[977, 316],
       [123, 334]], dtype=int64)

# S V M

In [387]:
from sklearn.svm import SVC
SVMclassifier = SVC(kernel='linear')#SVC(kernel='rbf')
SVMclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [388]:
# Predicting the Test set results
y_pred = SVMclassifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [389]:
SVMclassifier.score(X_test,y_test)

0.7971428571428572

In [339]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1163,  130],
       [ 225,  232]], dtype=int64)

# Decision Tree


In [393]:
X = data.iloc[:, 2:9].values
y = data.iloc[:, 10].values

In [404]:
data.head()

SeniorCitizen  Partner  Dependents        tenure  OnlineSecurity  \
20            1.0        0           0 -2.033755e-16               0   
30            1.0        1           0  1.572534e+00               1   
31            1.0        1           0 -1.285841e+00               0   
34            1.0        0           0 -2.033755e-16               0   
47            0.0        0           0 -1.285841e+00               0   

    TechSupport  Contract  PaperlessBilling  MonthlyCharges  TotalCharges  \
20            0         0                 1       -0.834046     -0.990429   
30            1         2                 1        1.049972      1.979662   
31            0         0                 1        1.021729     -0.927736   
34            0         0                 0       -0.647970     -0.987956   
47            0         0                 1        0.528295     -0.944292   

    Churn  
20      1  
30      0  
31      0  
34      0  
47      1

SeniorCitizen  Partner  Dependents        tenure  OnlineSecurity  \
20            1.0        0           0 -2.033755e-16               0   
30            1.0        1           0  1.572534e+00               1   
31            1.0        1           0 -1.285841e+00               0   
34            1.0        0           0 -2.033755e-16               0   
47            0.0        0           0 -1.285841e+00               0   

    TechSupport  Contract  PaperlessBilling  MonthlyCharges  TotalCharges  \
20            0         0                 1       -0.834046     -0.990429   
30            1         2                 1        1.049972      1.979662   
31            0         0                 1        1.021729     -0.927736   
34            0         0                 0       -0.647970     -0.987956   
47            0         0                 1        0.528295     -0.944292   

    Churn  
20      1  
30      0  
31      0  
34      0  
47      1

In [394]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [395]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [396]:
from sklearn.tree import DecisionTreeClassifier
DTclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DTclassifier.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [397]:
y_pred = DTclassifier.predict(X_test)
y_pred 

array([1, 0, 0, ..., 0, 0, 0])

In [398]:
DTclassifier.score(X_test,y_test)

0.728

In [399]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1060,  233],
       [ 243,  214]], dtype=int64)

In [401]:
from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator


from pyspark.ml.classification import RandomForestClassifier

#Create the model
rmClassifier = RandomForestClassifier(labelCol="indexed",featuresCol="pcaFeature")
rmModel = rmClassifier.fit(trainingData)


ModuleNotFoundError: No module named 'pyspark'

In [402]:
from pyspark.ml.classification import RandomForestClassifier

ModuleNotFoundError: No module named 'pyspark'

In [403]:
from pyspark.ml.classification import MultilayerPerceptronClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

ModuleNotFoundError: No module named 'pyspark'